In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
scale = StandardScaler()

In [3]:
df = pd.read_csv("dataset/testo-1.csv")
df

           Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [4]:
df['Volume'] = df['Volume'] / 1000
df

           Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo     1.0     790   99
1   Mitsubishi  Space Star     1.2    1160   95
2        Skoda      Citigo     1.0     929   95
3         Fiat         500     0.9     865   90
4         Mini      Cooper     1.5    1140  105
5           VW         Up!     1.0     929  105
6        Skoda       Fabia     1.4    1109   90
7     Mercedes     A-Class     1.5    1365   92
8         Ford      Fiesta     1.5    1112   98
9         Audi          A1     1.6    1150   99
10     Hyundai         I20     1.1     980   99
11      Suzuki       Swift     1.3     990  101
12        Ford      Fiesta     1.0    1112   99
13       Honda       Civic     1.6    1252   94
14      Hundai         I30     1.6    1326   97
15        Opel       Astra     1.6    1330   97
16         BMW           1     1.6    1365   99
17       Mazda           3     2.2    1280  104
18       Skoda       Rapid     1.6    1119  104
19        Ford       Focus     2.0    1328  105
20        Ford      Mondeo     1.6    1584   94
21        Opel    Insignia     2.0    1428   99
22    Mercedes     C-Class     2.1    1365   99
23       Skoda     Octavia     1.6    1415   99
24       Volvo         S60     2.0    1415   99
25    Mercedes         CLA     1.5    1465  102
26        Audi          A4     2.0    1490  104
27        Audi          A6     2.0    1725  114
28       Volvo         V70     1.6    1523  109
29         BMW           5     2.0    1705  114
30    Mercedes     E-Class     2.1    1605  115
31       Volvo        XC70     2.0    1746  117
32        Ford       B-Max     1.6    1235  104
33         BMW         216     1.6    1390  108
34        Opel      Zafira     1.6    1405  109
35    Mercedes         SLK     2.5    1395  120

In [6]:
X = df[['Weight', 'Volume']]
y = df['CO2']

In [7]:
model = LinearRegression()

In [8]:
model.fit(X, y)

LinearRegression()

In [9]:
print(model.predict([[2300, 1.3]]))

[107.2087328]

C:\Users\Fadri\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [13]:
scaledX = scale.fit_transform(X)
print(scaledX)

[[-2.10389253 -1.59336644]
 [-0.55407235 -1.07190106]
 [-1.52166278 -1.59336644]
 [-1.78973979 -1.85409913]
 [-0.63784641 -0.28970299]
 [-1.52166278 -1.59336644]
 [-0.76769621 -0.55043568]
 [ 0.3046118  -0.28970299]
 [-0.7551301  -0.28970299]
 [-0.59595938 -0.0289703 ]
 [-1.30803892 -1.33263375]
 [-1.26615189 -0.81116837]
 [-0.7551301  -1.59336644]
 [-0.16871166 -0.0289703 ]
 [ 0.14125238 -0.0289703 ]
 [ 0.15800719 -0.0289703 ]
 [ 0.3046118  -0.0289703 ]
 [-0.05142797  1.53542584]
 [-0.72580918 -0.0289703 ]
 [ 0.14962979  1.01396046]
 [ 1.2219378  -0.0289703 ]
 [ 0.5685001   1.01396046]
 [ 0.3046118   1.27469315]
 [ 0.51404696 -0.0289703 ]
 [ 0.51404696  1.01396046]
 [ 0.72348212 -0.28970299]
 [ 0.8281997   1.01396046]
 [ 1.81254495  1.01396046]
 [ 0.96642691 -0.0289703 ]
 [ 1.72877089  1.01396046]
 [ 1.30990057  1.27469315]
 [ 1.90050772  1.01396046]
 [-0.23991961 -0.0289703 ]
 [ 0.40932938 -0.0289703 ]
 [ 0.47215993 -0.0289703 ]
 [ 0.4302729   2.31762392]]

In [11]:
model.fit(scaledX, y)

LinearRegression()

In [12]:
scaled = scale.transform([[2300, 1.3]])
print(model.predict([scaled[0]]))

[107.2087328]

C:\Users\Fadri\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(